/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_erikge_gnandroid_NativeInterface */

#ifndef _Included_com_erikge_gnandroid_NativeInterface
#define _Included_com_erikge_gnandroid_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_erikge_gnandroid_NativeInterface
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_erikge_gnandroid_NativeInterface_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
